"""add parent_agent_id

Revision ID: 18e93e864c33
Revises: 40ccca827ee8
Create Date: 2026-03-21 18:25:05.547179

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "18e93e864c33"
down_revision: str | Sequence[str] | None = "40ccca827ee8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("agents", sa.Column("parent_agent_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "fk_agents_parent_agent_id",
        "agents",
        "agents",
        ["parent_agent_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_agents_parent_agent_id", "agents", type_="foreignkey")
    op.drop_column("agents", "parent_agent_id")
    # ### end Alembic commands ###
