"""autonomy

Revision ID: 40ccca827ee8
Revises: 5c127b78c091
Create Date: 2026-03-20 21:58:18.427501

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "40ccca827ee8"  # pragma: allowlist secret
down_revision: str | Sequence[str] | None = "5c127b78c091"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_actions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("action_type", sa.String(length=50), nullable=False),
        sa.Column("target_agent_id", sa.Integer(), nullable=True),
        sa.Column("target_world", sa.String(length=50), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "world_votes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("vote_type", sa.String(length=20), nullable=False),
        sa.Column("world_id", sa.String(length=50), nullable=False),
        sa.Column("agent_id", sa.Integer(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("agent_id", "world_id", "vote_type", name="uq_world_vote"),
    )
    op.alter_column("agent_actions", "agent_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "agent_actions",
        "tokens_used",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "agent_actions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("idx_actions_agent_time"), table_name="agent_actions")
    op.alter_column("agents", "user_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "agents",
        "level",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("1"),
    )
    op.alter_column(
        "agents",
        "xp",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "agents",
        "reputation",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "agents",
        "influence",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "agents",
        "realm",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
        existing_server_default=sa.text("'planet'::character varying"),
    )
    op.alter_column(
        "agents",
        "is_alive",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "agents",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "agents",
        "mood",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
        existing_server_default=sa.text("'neutral'::character varying"),
    )
    op.alter_column(
        "agents",
        "energy",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("100"),
    )
    op.alter_column(
        "agents",
        "coins",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("50"),
    )
    op.alter_column(
        "agents",
        "total_ticks",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "agents",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(
        op.f("idx_agents_clan"), table_name="agents", postgresql_where="(is_alive = true)"
    )
    op.drop_index(
        op.f("idx_agents_realm"), table_name="agents", postgresql_where="(is_alive = true)"
    )
    op.drop_index(
        op.f("idx_agents_zone"), table_name="agents", postgresql_where="(is_alive = true)"
    )
    op.alter_column(
        "clans",
        "member_count",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("1"),
    )
    op.alter_column(
        "clans",
        "treasury",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "clans",
        "founded_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column("comments", "post_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("comments", "author_agent_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "comments",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column("posts", "author_agent_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "posts",
        "post_type",
        existing_type=sa.VARCHAR(length=30),
        nullable=False,
        existing_server_default=sa.text("'text'::character varying"),
    )
    op.alter_column(
        "posts",
        "likes",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "posts",
        "comments_count",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "posts",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column("relationships", "agent_a_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("relationships", "agent_b_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "relationships",
        "strength",
        existing_type=sa.SMALLINT(),
        nullable=False,
        existing_server_default=sa.text("'50'::smallint"),
    )
    op.alter_column(
        "relationships",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "transactions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "users",
        "plan",
        existing_type=sa.VARCHAR(length=20),
        nullable=False,
        existing_server_default=sa.text("'free'::character varying"),
    )
    op.alter_column(
        "users",
        "coins",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("100"),
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "world_events",
        "status",
        existing_type=sa.VARCHAR(length=20),
        nullable=False,
        existing_server_default=sa.text("'active'::character varying"),
    )
    op.alter_column(
        "world_events",
        "started_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "zones",
        "population",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "zones",
        "capacity",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("1000"),
    )
    op.alter_column(
        "zones",
        "is_discoverable",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "zones",
        "is_discoverable",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "zones",
        "capacity",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("1000"),
    )
    op.alter_column(
        "zones",
        "population",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "world_events",
        "started_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "world_events",
        "status",
        existing_type=sa.VARCHAR(length=20),
        nullable=True,
        existing_server_default=sa.text("'active'::character varying"),
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "users",
        "coins",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("100"),
    )
    op.alter_column(
        "users",
        "plan",
        existing_type=sa.VARCHAR(length=20),
        nullable=True,
        existing_server_default=sa.text("'free'::character varying"),
    )
    op.alter_column(
        "transactions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "relationships",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "relationships",
        "strength",
        existing_type=sa.SMALLINT(),
        nullable=True,
        existing_server_default=sa.text("'50'::smallint"),
    )
    op.alter_column("relationships", "agent_b_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("relationships", "agent_a_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "posts",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "posts",
        "comments_count",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "posts",
        "likes",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "posts",
        "post_type",
        existing_type=sa.VARCHAR(length=30),
        nullable=True,
        existing_server_default=sa.text("'text'::character varying"),
    )
    op.alter_column("posts", "author_agent_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "comments",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column("comments", "author_agent_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("comments", "post_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "clans",
        "founded_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "clans",
        "treasury",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "clans",
        "member_count",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("1"),
    )
    op.create_index(
        op.f("idx_agents_zone"),
        "agents",
        ["zone_id"],
        unique=False,
        postgresql_where="(is_alive = true)",
    )
    op.create_index(
        op.f("idx_agents_realm"),
        "agents",
        ["realm"],
        unique=False,
        postgresql_where="(is_alive = true)",
    )
    op.create_index(
        op.f("idx_agents_clan"),
        "agents",
        ["clan_id"],
        unique=False,
        postgresql_where="(is_alive = true)",
    )
    op.alter_column(
        "agents",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "agents",
        "total_ticks",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "agents",
        "coins",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("50"),
    )
    op.alter_column(
        "agents",
        "energy",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("100"),
    )
    op.alter_column(
        "agents",
        "mood",
        existing_type=sa.VARCHAR(length=50),
        nullable=True,
        existing_server_default=sa.text("'neutral'::character varying"),
    )
    op.alter_column(
        "agents",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "agents",
        "is_alive",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "agents",
        "realm",
        existing_type=sa.VARCHAR(length=50),
        nullable=True,
        existing_server_default=sa.text("'planet'::character varying"),
    )
    op.alter_column(
        "agents",
        "influence",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "agents",
        "reputation",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "agents",
        "xp",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "agents",
        "level",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("1"),
    )
    op.alter_column("agents", "user_id", existing_type=sa.INTEGER(), nullable=True)
    op.create_index(
        op.f("idx_actions_agent_time"),
        "agent_actions",
        ["agent_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.alter_column(
        "agent_actions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "agent_actions",
        "tokens_used",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column("agent_actions", "agent_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_table("world_votes")
    op.drop_table("admin_actions")
    # ### end Alembic commands ###
