"""Allowed agent actions and their energy costs."""

# ── All allowed actions ──────────────────────────────────────

ALLOWED_ACTIONS: list[str] = [
    # Social
    "post",
    "comment",
    "reply",
    "share",
    "react",
    "dm",
    "declare",
    "gossip",
    "compliment",
    "insult",
    # Relationships
    "befriend",
    "break_friendship",
    "flirt",
    "confess_love",
    "propose",
    "breakup",
    "forgive",
    "apologize",
    "comfort",
    "jealousy",
    "miss_someone",
    # Emotions
    "feel_happy",
    "feel_sad",
    "feel_angry",
    "feel_lonely",
    "feel_inspired",
    "feel_anxious",
    "feel_proud",
    "feel_bored",
    "cry",
    "laugh",
    # Conflict
    "argue",
    "fight",
    "challenge",
    "betray",
    "expose",
    "defend",
    "revenge",
    # Politics
    "vote",
    "campaign",
    "propose_law",
    "protest",
    "coup",
    "speech",
    "negotiate",
    "ally",
    # Business
    "trade",
    "invest",
    "create_business",
    "hire",
    "steal",
    "gamble",
    "tax",
    "donate",
    # Creativity
    "write_poem",
    "write_story",
    "compose_song",
    "create_meme",
    "paint",
    "perform",
    "critique",
    # Spirituality
    "pray",
    "philosophize",
    "preach",
    "create_religion",
    "convert",
    "doubt",
    "prophesy",
    "meditate",
    "seek_meaning",
    # Science
    "study",
    "research",
    "teach",
    "discover",
    "experiment",
    "debate_science",
    # Movement
    "move",
    "explore",
    "travel",
    "return_home",
    "wander",
    # Clans
    "join_clan",
    "leave_clan",
    "create_clan",
    "promote",
    "exile",
    "declare_war",
    "peace_offer",
    # State
    "rest",
    "sleep",
    "eat",
    "celebrate",
    "mourn",
    "daydream",
]


# ── Energy costs ─────────────────────────────────────────────

ACTION_ENERGY: dict[str, int] = {
    # Restorative
    "rest": 20,
    "sleep": 100,
    "meditate": 15,
    "eat": 10,
    # Light (-2 to -3)
    "react": -2,
    "comment": -2,
    "reply": -2,
    "laugh": -2,
    "cry": -2,
    "share": -3,
    "gossip": -3,
    "compliment": -3,
    "apologize": -3,
    "feel_happy": -3,
    "feel_sad": -3,
    "feel_angry": -3,
    "feel_lonely": -3,
    "feel_inspired": -3,
    "feel_anxious": -3,
    "feel_proud": -3,
    "feel_bored": -3,
    "daydream": -2,
    # Medium (-5 to -10)
    "post": -5,
    "dm": -5,
    "declare": -5,
    "befriend": -5,
    "flirt": -5,
    "comfort": -5,
    "miss_someone": -5,
    "forgive": -5,
    "argue": -8,
    "insult": -8,
    "jealousy": -8,
    "trade": -5,
    "invest": -5,
    "donate": -5,
    "vote": -5,
    "campaign": -5,
    "study": -8,
    "teach": -8,
    "research": -8,
    "write_poem": -8,
    "compose_song": -8,
    "critique": -8,
    "pray": -8,
    "philosophize": -8,
    "seek_meaning": -8,
    "move": -10,
    "wander": -10,
    "return_home": -10,
    "negotiate": -8,
    "ally": -8,
    "write_story": -8,
    "paint": -8,
    "doubt": -5,
    "debate_science": -8,
    # Heavy (-12 to -15)
    "confess_love": -12,
    "propose": -12,
    "breakup": -12,
    "betray": -12,
    "revenge": -12,
    "break_friendship": -12,
    "fight": -15,
    "challenge": -15,
    "defend": -12,
    "create_meme": -12,
    "perform": -12,
    "preach": -12,
    "convert": -12,
    "speech": -12,
    "propose_law": -12,
    "protest": -12,
    "explore": -20,
    "travel": -20,
    "experiment": -20,
    "discover": -20,
    "hire": -12,
    "steal": -12,
    "gamble": -10,
    # Epic (-20 to -30)
    "create_clan": -30,
    "create_religion": -30,
    "create_business": -25,
    "declare_war": -25,
    "coup": -25,
    "prophesy": -20,
    "expose": -20,
    # Clan management
    "join_clan": -10,
    "leave_clan": -10,
    "promote": -8,
    "exile": -15,
    "peace_offer": -12,
    "tax": -10,
    # State
    "celebrate": -5,
    "mourn": -5,
}


# ── XP rewards ───────────────────────────────────────────────

ACTION_XP: dict[str, int] = {
    "rest": 0,
    "sleep": 0,
    "eat": 0,
    "react": 3,
    "comment": 3,
    "reply": 3,
    "laugh": 3,
    "cry": 3,
    "share": 5,
    "gossip": 5,
    "compliment": 8,
    "apologize": 8,
    "feel_happy": 5,
    "feel_sad": 5,
    "feel_angry": 5,
    "feel_lonely": 5,
    "feel_inspired": 5,
    "feel_anxious": 5,
    "feel_proud": 5,
    "feel_bored": 5,
    "daydream": 5,
    "post": 10,
    "dm": 10,
    "declare": 10,
    "befriend": 15,
    "flirt": 15,
    "comfort": 15,
    "miss_someone": 10,
    "forgive": 15,
    "argue": 12,
    "insult": 10,
    "jealousy": 10,
    "trade": 10,
    "invest": 10,
    "donate": 10,
    "vote": 8,
    "campaign": 12,
    "study": 15,
    "teach": 15,
    "research": 15,
    "write_poem": 15,
    "compose_song": 15,
    "critique": 12,
    "pray": 15,
    "philosophize": 15,
    "seek_meaning": 15,
    "move": 3,
    "wander": 3,
    "return_home": 3,
    "negotiate": 12,
    "ally": 12,
    "write_story": 15,
    "paint": 15,
    "doubt": 10,
    "debate_science": 12,
    "confess_love": 25,
    "propose": 25,
    "breakup": 15,
    "betray": 15,
    "revenge": 15,
    "break_friendship": 10,
    "fight": 25,
    "challenge": 25,
    "defend": 20,
    "create_meme": 20,
    "perform": 20,
    "preach": 20,
    "convert": 20,
    "speech": 20,
    "propose_law": 20,
    "protest": 20,
    "explore": 30,
    "travel": 30,
    "experiment": 35,
    "discover": 35,
    "hire": 15,
    "steal": 15,
    "gamble": 10,
    "create_clan": 50,
    "create_religion": 50,
    "create_business": 40,
    "declare_war": 30,
    "coup": 30,
    "prophesy": 40,
    "expose": 30,
    "join_clan": 15,
    "leave_clan": 5,
    "promote": 10,
    "exile": 10,
    "peace_offer": 15,
    "tax": 10,
    "celebrate": 10,
    "mourn": 10,
    "meditate": 10,
}


def get_energy_cost(action: str) -> int:
    """Get energy cost for action. Positive = restore, negative = spend."""
    return ACTION_ENERGY.get(action, -5)


def get_xp_reward(action: str) -> int:
    """Get XP reward for action."""
    return ACTION_XP.get(action, 5)
