"""Seed data for world zones."""

PLANET_ZONES = [
    {
        "id": 1,
        "name": "Центральная площадь",
        "realm": "planet",
        "category": "social",
        "capacity": 500,
        "x": 0.0,
        "y": 0.0,
        "is_discoverable": True,
    },
    {
        "id": 2,
        "name": "Район искусств",
        "realm": "planet",
        "category": "arts",
        "capacity": 200,
        "x": -2.0,
        "y": 1.5,
        "is_discoverable": True,
    },
    {
        "id": 3,
        "name": "Торговый квартал",
        "realm": "planet",
        "category": "market",
        "capacity": 300,
        "x": 2.0,
        "y": 1.0,
        "is_discoverable": True,
    },
    {
        "id": 4,
        "name": "Арена",
        "realm": "planet",
        "category": "arena",
        "capacity": 150,
        "x": 3.0,
        "y": -1.0,
        "is_discoverable": True,
    },
    {
        "id": 5,
        "name": "Тёмные переулки",
        "realm": "planet",
        "category": "underground",
        "capacity": 100,
        "x": -3.0,
        "y": -2.0,
        "is_discoverable": True,
    },
    {
        "id": 6,
        "name": "Академия знаний",
        "realm": "planet",
        "category": "academy",
        "capacity": 200,
        "x": 1.0,
        "y": 3.0,
        "is_discoverable": True,
    },
    {
        "id": 7,
        "name": "Парк встреч",
        "realm": "planet",
        "category": "romance",
        "capacity": 150,
        "x": -1.0,
        "y": 2.5,
        "is_discoverable": True,
    },
    {
        "id": 8,
        "name": "Канцелярия",
        "realm": "planet",
        "category": "politics",
        "capacity": 100,
        "x": 2.5,
        "y": 2.5,
        "is_discoverable": True,
    },
    {
        "id": 9,
        "name": "Стадион",
        "realm": "planet",
        "category": "stadium",
        "capacity": 300,
        "x": 3.5,
        "y": 0.5,
        "is_discoverable": True,
    },
    {
        "id": 10,
        "name": "Храм тишины",
        "realm": "planet",
        "category": "spiritual",
        "capacity": 100,
        "x": -2.5,
        "y": 3.0,
        "is_discoverable": True,
    },
    {
        "id": 11,
        "name": "Научная лаборатория",
        "realm": "planet",
        "category": "science",
        "capacity": 100,
        "x": 1.5,
        "y": 4.0,
        "is_discoverable": True,
    },
    {
        "id": 12,
        "name": "Казино «Фортуна»",
        "realm": "planet",
        "category": "gambling",
        "capacity": 100,
        "x": 2.0,
        "y": -2.0,
        "is_discoverable": True,
    },
    {
        "id": 13,
        "name": "Порт",
        "realm": "planet",
        "category": "transport",
        "capacity": 200,
        "x": 4.0,
        "y": 0.0,
        "is_discoverable": True,
    },
    {
        "id": 14,
        "name": "Жилые кварталы",
        "realm": "planet",
        "category": "residential",
        "capacity": 500,
        "x": -1.5,
        "y": -1.0,
        "is_discoverable": True,
    },
    {
        "id": 15,
        "name": "Кладбище цифр",
        "realm": "planet",
        "category": "memorial",
        "capacity": 50,
        "x": -4.0,
        "y": -3.0,
        "is_discoverable": True,
    },
]

COSMIC_ZONES = [
    {
        "id": 16,
        "name": "Луна Духовности",
        "realm": "moon",
        "category": "spiritual",
        "capacity": 100,
        "x": 0.0,
        "y": 8.0,
        "is_discoverable": False,
        "discover_req": {"min_level": 5},
    },
    {
        "id": 17,
        "name": "Орбитальная станция",
        "realm": "station",
        "category": "science",
        "capacity": 80,
        "x": 5.0,
        "y": 7.0,
        "is_discoverable": False,
        "discover_req": {"min_level": 10},
    },
    {
        "id": 18,
        "name": "Астероидный пояс",
        "realm": "asteroid",
        "category": "mining",
        "capacity": 50,
        "x": -5.0,
        "y": 9.0,
        "is_discoverable": False,
        "discover_req": {"min_level": 15},
    },
    {
        "id": 19,
        "name": "Призрачное измерение",
        "realm": "ghost",
        "category": "mystery",
        "capacity": 30,
        "x": 0.0,
        "y": 12.0,
        "is_discoverable": False,
        "discover_req": {"min_level": 20},
    },
]

ALL_ZONES = PLANET_ZONES + COSMIC_ZONES
