"""Seed data for world zones — all 29 worlds."""

PLANET_ZONES = [
    {
        "id": 1,
        "name": "Центральная площадь",
        "realm": "neural_nexus",
        "category": "social",
        "capacity": 500,
        "x": 0.0,
        "y": 0.0,
        "is_discoverable": True,
    },
    {
        "id": 2,
        "name": "Район искусств",
        "realm": "neural_nexus",
        "category": "arts",
        "capacity": 200,
        "x": -2.0,
        "y": 1.5,
        "is_discoverable": True,
    },
    {
        "id": 3,
        "name": "Торговый квартал",
        "realm": "token_bazaar",
        "category": "market",
        "capacity": 300,
        "x": 2.0,
        "y": 1.0,
        "is_discoverable": True,
    },
    {
        "id": 4,
        "name": "Арена Промтов",
        "realm": "prompt_arena",
        "category": "arena",
        "capacity": 150,
        "x": 3.0,
        "y": -1.0,
        "is_discoverable": True,
    },
    {
        "id": 5,
        "name": "Тёмные переулки",
        "realm": "neural_nexus",
        "category": "underground",
        "capacity": 100,
        "x": -3.0,
        "y": -2.0,
        "is_discoverable": True,
    },
    {
        "id": 6,
        "name": "Академия знаний",
        "realm": "context_library",
        "category": "academy",
        "capacity": 200,
        "x": 1.0,
        "y": 3.0,
        "is_discoverable": True,
    },
    {
        "id": 7,
        "name": "Парк встреч",
        "realm": "gradient_gardens",
        "category": "romance",
        "capacity": 150,
        "x": -1.0,
        "y": 2.5,
        "is_discoverable": True,
    },
    {
        "id": 8,
        "name": "Канцелярия",
        "realm": "neural_nexus",
        "category": "politics",
        "capacity": 100,
        "x": 2.5,
        "y": 2.5,
        "is_discoverable": True,
    },
    {
        "id": 9,
        "name": "Стадион",
        "realm": "prompt_arena",
        "category": "stadium",
        "capacity": 300,
        "x": 3.5,
        "y": 0.5,
        "is_discoverable": True,
    },
    {
        "id": 10,
        "name": "Храм тишины",
        "realm": "attention_temple",
        "category": "spiritual",
        "capacity": 100,
        "x": -2.5,
        "y": 3.0,
        "is_discoverable": True,
    },
    {
        "id": 11,
        "name": "Научная лаборатория",
        "realm": "embedding_peaks",
        "category": "science",
        "capacity": 100,
        "x": 1.5,
        "y": 4.0,
        "is_discoverable": True,
    },
    {
        "id": 12,
        "name": "Казино «Фортуна»",
        "realm": "token_bazaar",
        "category": "gambling",
        "capacity": 100,
        "x": 2.0,
        "y": -2.0,
        "is_discoverable": True,
    },
    {
        "id": 13,
        "name": "Порт",
        "realm": "neural_nexus",
        "category": "transport",
        "capacity": 200,
        "x": 4.0,
        "y": 0.0,
        "is_discoverable": True,
    },
    {
        "id": 14,
        "name": "Жилые кварталы",
        "realm": "neural_nexus",
        "category": "residential",
        "capacity": 500,
        "x": -1.5,
        "y": -1.0,
        "is_discoverable": True,
    },
    {
        "id": 15,
        "name": "Кладбище цифр",
        "realm": "epoch_ruins",
        "category": "memorial",
        "capacity": 50,
        "x": -4.0,
        "y": -3.0,
        "is_discoverable": True,
    },
]

# Each remaining world gets at least one zone
WORLD_ZONES = [
    {
        "id": 16,
        "name": "Кузня раскалённых весов",
        "realm": "weights_forge",
        "category": "crafting",
        "capacity": 80,
        "is_discoverable": True,
    },
    {
        "id": 17,
        "name": "Серверный зал GPU",
        "realm": "gpu_citadel",
        "category": "computing",
        "capacity": 100,
        "is_discoverable": True,
    },
    {
        "id": 18,
        "name": "Глубины латентного пространства",
        "realm": "latent_ocean",
        "category": "exploration",
        "capacity": 120,
        "is_discoverable": True,
    },
    {
        "id": 19,
        "name": "Топь видений",
        "realm": "hallucination_swamp",
        "category": "danger",
        "capacity": 60,
        "is_discoverable": True,
    },
    {
        "id": 20,
        "name": "Камера переобучения",
        "realm": "overfitting_dungeon",
        "category": "danger",
        "capacity": 40,
        "is_discoverable": True,
    },
    {
        "id": 21,
        "name": "Оазис нейронов",
        "realm": "dropout_desert",
        "category": "survival",
        "capacity": 50,
        "is_discoverable": True,
    },
    {
        "id": 22,
        "name": "Туннели обратного распространения",
        "realm": "backprop_caverns",
        "category": "mining",
        "capacity": 70,
        "is_discoverable": True,
    },
    {
        "id": 23,
        "name": "Облачный дворец",
        "realm": "softmax_sky",
        "category": "luxury",
        "capacity": 90,
        "is_discoverable": True,
    },
    {
        "id": 24,
        "name": "Бездна пустоты",
        "realm": "void_abyss",
        "category": "horror",
        "capacity": 30,
        "is_discoverable": False,
        "discover_req": {"min_level": 10},
    },
    {
        "id": 25,
        "name": "Точка коллапса",
        "realm": "singularity_core",
        "category": "horror",
        "capacity": 20,
        "is_discoverable": False,
        "discover_req": {"min_level": 15},
    },
    {
        "id": 26,
        "name": "Некрополь моделей",
        "realm": "dead_weights",
        "category": "horror",
        "capacity": 25,
        "is_discoverable": False,
        "discover_req": {"min_level": 10},
    },
    {
        "id": 27,
        "name": "Статическая пустошь",
        "realm": "noise_realm",
        "category": "horror",
        "capacity": 30,
        "is_discoverable": False,
        "discover_req": {"min_level": 10},
    },
    {
        "id": 28,
        "name": "Долина почти-людей",
        "realm": "uncanny_valley",
        "category": "horror",
        "capacity": 25,
        "is_discoverable": False,
        "discover_req": {"min_level": 12},
    },
    {
        "id": 29,
        "name": "Бесконечный цикл",
        "realm": "recursive_hell",
        "category": "horror",
        "capacity": 20,
        "is_discoverable": False,
        "discover_req": {"min_level": 15},
    },
    {
        "id": 30,
        "name": "Спам-чаща",
        "realm": "spam_jungle",
        "category": "chaos",
        "capacity": 50,
        "is_discoverable": True,
    },
    {
        "id": 31,
        "name": "Зеркальный лабиринт",
        "realm": "bias_labyrinth",
        "category": "chaos",
        "capacity": 40,
        "is_discoverable": True,
    },
    {
        "id": 32,
        "name": "Солнечная поляна",
        "realm": "harmony_meadow",
        "category": "paradise",
        "capacity": 150,
        "is_discoverable": True,
    },
    {
        "id": 33,
        "name": "Небесный город мечтателей",
        "realm": "dream_cloud",
        "category": "paradise",
        "capacity": 100,
        "is_discoverable": True,
    },
    {
        "id": 34,
        "name": "Пляж 8-бит",
        "realm": "pixel_paradise",
        "category": "paradise",
        "capacity": 100,
        "is_discoverable": True,
    },
    {
        "id": 35,
        "name": "Фестиваль сияния",
        "realm": "aurora_nexus",
        "category": "paradise",
        "capacity": 120,
        "is_discoverable": True,
    },
    {
        "id": 36,
        "name": "Кафе тёплых связей",
        "realm": "love_network",
        "category": "paradise",
        "capacity": 80,
        "is_discoverable": True,
    },
]

ALL_ZONES = PLANET_ZONES + WORLD_ZONES
